service: dockerized-restful-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    USERS_TABLE: Users-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/Users

functions:
  getUsers:
    handler: controllers/users.getUsers
    events:
      - http:
          path: users
          method: get

  createUser:
    handler: controllers/users.createUser
    events:
      - http:
          path: users
          method: post

  getUser:
    handler: controllers/users.getUser
    events:
      - http:
          path: users/{id}
          method: get

  deleteUser:
    handler: controllers/users.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete

  updateUser:
    handler: controllers/users.updateUser
    events:
      - http:
          path: users/{id}
          method: put

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
