service: dockerized-restful-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x # Use the correct Node.js version
  region: us-east-1
  stage: ${opt:stage, 'dev'} # Default to 'dev' stage if not specified
  environment:
    USERS_TABLE: Users-${self:provider.stage} # DynamoDB table name

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post

  getUsers:
    handler: handler.getUsers
    events:
      - http:
          path: users
          method: get

  getUser:
    handler: handler.getUser
    events:
      - http:
          path: users/{id}
          method: get

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: Users
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: Users
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
